[build]
  publish = "dist/"
  command = "yarn elm make src/Main.elm --output=dist/index.html && cp src/style.css dist/ && cp -r src/ISMB_ECCB_2023_All_sessions.json dist/"

[build.environment]
  ELM_HOME = "$NETLIFY_BUILD_BASE/cache/elm"
